# Travis CI file, that integrates with coveralls for reporting test coverage.

language: python

python:
  - "2.7"

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false
